//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutossisEntities : DbContext
    {
        public AutossisEntities()
            : base("name=AutossisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conmgr> Conmgr { get; set; }
        public virtual DbSet<Package> Package { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<PackageControl> PackageControl { get; set; }
        public virtual DbSet<TaskExecuteLog> TaskExecuteLog { get; set; }
        public virtual DbSet<TaskExecuteLogDetail> TaskExecuteLogDetail { get; set; }
    }
}
