//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskId { get; set; }
        public string TaskName { get; set; }
        public int SourceConmgrId { get; set; }
        public int TargetConmgrId { get; set; }
        public string SourceTableName { get; set; }
        public string TargetTableName { get; set; }
        public string SqlCommand { get; set; }
        public int PackageId { get; set; }
        public string TaskType { get; set; }
    
        public virtual Conmgr Conmgr { get; set; }
        public virtual Conmgr Conmgr1 { get; set; }
        public virtual Package Package { get; set; }
    }
}
